#!/usr/bin/env bash

filename='my-file'
# echo "$filename".{txt,jpeg,mov}

arr=("$filename."{txt,jpeg,mov})

for item in "${arr[@]}"; do
		echo "$item"
done
arr=(/etc/{foo,bar}/{1,2,3}.txt)

for item in "${arr[@]}"; do
		echo "$item"
done
